import seaborn as sns
import pandas as pd

titanic = sns.load_dataset("titanic")

print()
print("Using the .shape command provides the information:")
print(titanic.shape)
print()
print("Using the .columns command provides the information:")
print(titanic.columns)
print()
print("Using the .dtypes command provides the information:")
print(titanic.dtypes)
print()
print("Gathering Sex and Survived sections together provides information:")
print(titanic[["sex","survived"]])
print()
print("Gathering the head of the previous data provides information:")
print(titanic[["sex","survived"]].head)
print()
print("Gathering all the information for the first five items provides information:")
print(titanic[0:5])
print()
print("Using the .loc function provides the information:")
print(titanic.loc[0:5,["pclass","age"]])
print()
print("Using the iloc command provides the information:")
print(titanic.iloc[0:5,0:5])
print()
