import seaborn as sns
import pandas as pd

titanic = sns.load_dataset("titanic")

print(titanic.shape)
print()
print(titanic.columns)
print()
print(titanic.dtypes)
print()
print(titanic.index)
print()
print(titanic.size)
print()
print(titanic.values)
print()
print(titanic.mean)
print()
print(titanic.min)
print()
print(titanic[["sex","survived"]])
print()
print(titanic[["sex","survived"]].head())
print()
print(titanic[0:5])
print()
print(titanic.loc[0:5,["pclass","age"]])
print()
print(titanic.iloc[0:5,0:5])
print()
